### ISSUE TITLE
Using parenthesis instead of curly braces for function body breaks further syntax highlighting

### ISSUE THREAD

**Issue by alexr00** [jeff-hykin/better-shell-syntax#49] opened 2023-03-07 15:35 UTC
## The code with a problem is (notice lines 3 and 5 where `(` and `)` are used instead of `{` and `}`): 
```shell
#!/bin/sh

_get_current_ip() (
    curl -s -f "https://avacyn.aerium.hr/ip" || exit 1
)

_ctype="Content-Type: application/json"
```

## It looks like:
![image](https://user-images.githubusercontent.com/38270282/223469985-7384b33e-7dda-4350-8fde-b186cbb20870.png)

## It should look like:
![image](https://user-images.githubusercontent.com/38270282/223470138-597e23c5-c6f5-4148-aed0-f8a4b22c2eeb.png)

From @karabaja4 in https://github.com/microsoft/vscode/issues/176190#issuecomment-1455251249

**Comment by jeff-hykin** [comment] 2023-03-07 17:51
just recently fixed! (duplicate of #45 ) `v1.4.3`

**Closed by jeff-hykin** 2023-03-07 17:51 UTC
